trigger:
- main

pool:
  name: MyPools  # Specify the self-hosted agent pool
  demands:
    - agent.name -equals MyAgent  # Ensure the pipeline runs on your specific agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Specify the Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build the project'
  shell: cmd  # Use cmd.exe shell for Windows

- script: |
    mkdir "%AGENT_WORKFOLDER%\artifacts\react-build"
    xcopy /E /I build "%AGENT_WORKFOLDER%\artifacts\react-build\"
  displayName: 'Save build artifacts locally'
  shell: cmd  # Use cmd.exe shell for Windows
