trigger:
- main

pool:
  name: MyPools  # Specify the self-hosted agent pool name
  demands:
    - agent.name -equals MyAgent  # Ensure the pipeline runs on your specific agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version to install
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build the project'

- script: |
    npm start
  displayName: 'Run the application'

# Additional steps for artifacts and deployment
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'react-build'
  displayName: 'Publish Build Artifacts'
