trigger:
- main

pool:
  name: MyPools  # Specify the self-hosted agent pool name
  demands:
    - agent.name -equals MyAgent  # Ensure the pipeline runs on your specific agent

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Match Node.js version to your project's requirements
  displayName: 'Install Node.js'

# Step 2: Install dependencies and build the project
- script: |
    npm install
    npm run build
  displayName: 'Install Dependencies and Build'

# Step 3: Debug directory structure
- script: |
    dir "$(System.DefaultWorkingDirectory)"
    dir "$(System.DefaultWorkingDirectory)\build"
  displayName: 'Debug Directory Structure'

# Step 4: Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)\build'  # Use the full path to the build directory
    ArtifactName: 'react-build'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# (Optional) Add any deployment task if needed.
# For example, deploying to Azure App Service, static site hosting, etc.
